version: '3'
services:
  ui:
    build: ./ui
    container_name: ui
    restart: always
    depends_on:
      - database
    ports:
      - 3000:3000

  api:
    build: ./api
    container_name: api
    restart: always
    depends_on:
      - database
    ports:
      - 4000:4000
  
  database:
    build: ./database
    container_name: 'postgres'
    restart: always
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'liquor_sales'
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./database:/share/database

  pgadmin:
    build: ./pgadmin
    container_name: 'pgadmin'
    restart: always
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: 'root@gatech.edu'
      PGADMIN_DEFAULT_PASSWORD: 'root'
    ports:
      - '5050:80'

volumes:
  database-data: # named volumes can be managed easier using docker-compose